from django.conf.urls import patterns,url,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       
    (r'^$','core.views.main'),
    (r'^deadlines','core.views.deadlines'),
    (r'^mosaic','core.views.mosaic'),
    (r'^config','core.views.config'),
    (r'^profile','core.views.profile'),
    (r'^photo','core.views.photo'),
    (r'^appearance','core.views.appearance'),
    (r'^options','core.views.options'),
    (r'^place','core.views.place'),
    (r'^password','core.views.password'),
    (r'^integrations','core.views.integrations'),
    (r'^enter','core.views.authenticate'),
    (r'^leave','core.views.leave'),
    (r'^delete','core.views.delete'),
    (r'^userid','core.views.ids'),
    (r'^search','core.views.search'),
    (r'^explore','core.views.search'),
    (r'^known','core.views.explore'),
    (r'^activity','core.views.activity'),
    (r'^following','core.views.following'),
    (r'^follow','core.views.follow'),
    (r'^unfollow','core.views.unfollow'),
    (r'^twitter/post','core.views.twitter_post'),
    (r'^facebook/post','core.views.facebook_post'),
    (r'^facebook/event','core.views.facebook_event'),
    (r'^participate','core.views.participate'),
    (r'^tutorial','core.views.tutorial'),
    
    (r'^products','store.views.main'),
    (r'^store','store.views.init_store'),
    (r'^cart','store.views.cart'),
    (r'^cancel','store.views.cancel'),
    (r'^payment','store.views.payment'),
    (r'^discharge','store.views.discharge'),
    (r'^recharge','store.views.recharge'),
    (r'^balance','store.views.balance'),
    (r'^delivery','store.views.delivery'),
    (r'^correios','store.views.mail'),
    (r'^paypal','store.views.paypal_ipn'),
    
    (r'^spreadable','spread.views.spreadable'),
    (r'^spreaded','spread.views.spreaded'),
    (r'^spreadspread','spread.views.spreadspread'),
    (r'^spreads','spread.views.init_spread'),
    (r'^spread','spread.views.main'),
    (r'^playable','spread.views.playable'),
    (r'^images','spread.views.image'),
    (r'^image','spread.views.imageview'),
    (r'^event','spread.views.eventview'),
    (r'^pageview','spread.views.pageview'),
    (r'^pageedit','spread.views.pageedit'),
    (r'^calendar','spread.views.event'),
    (r'^contents','spread.views.content'),
    (r'^schedule','spread.views.schedule'),
    (r'^collection','spread.views.collection'),
    (r'^expose','spread.views.upload'),
    (r'^content','spread.views.collection'),
    (r'^pages','spread.views.page'),
    
    (r'^projects','promote.views.main'),
    (r'^create','promote.views.init_create'),
    (r'^backers','promote.views.backers'),
    (r'^movements','promote.views.movements'),
    (r'^promote','promote.views.promote'),
    (r'^project','promote.views.project'),
    (r'^linkproj','promote.views.link'),
    (r'^movement','promote.views.movement'),
    (r'^pledge','promote.views.pledge'),
    (r'^grab','promote.views.grab'),
    
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)
urlpatterns += staticfiles_urlpatterns()
